# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientfinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 160, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_active_users = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_active_users.setObjectName("label_active_users")
        self.verticalLayout.addWidget(self.label_active_users)
        self.label_active_users.setStyleSheet("background-color: cyan;")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setGeometry(QtCore.QRect(10, 50, 161, 481))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget_2.setStyleSheet("background-color: lightblue; border: 2px solid darkblue;")



        self.verticalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_3.setGeometry(QtCore.QRect(199, 59, 571, 441))
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget_3.setStyleSheet("background-color: lightgreen; border: 2px solid darkblue;")


        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(199, 59, 571, 441))
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setWidgetResizable(True)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 571, 441))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollAreaWidgetContents.setStyleSheet("color: darkblue;")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.message = QtWidgets.QTextEdit(self.centralwidget)
        self.message.setStyleSheet("background-color: lightyellow; color: darkblue;")

        self.message.setGeometry(QtCore.QRect(200, 510, 491, 87))
        self.message.setObjectName("message")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 520, 71, 21))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_file.setGeometry(QtCore.QRect(620, 520, 71, 21))
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.pushButton_open_file.setText("Select Image")
        self.pushButton_open_file.clicked.connect(self.open_file_dialog)
        self.pushButton_open_file.setGeometry(QtCore.QRect(700, 520, 71, 21))
        self.pushButton.setGeometry(QtCore.QRect(620, 520, 71, 21))



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Application"))
        self.label_active_users.setText(_translate("MainWindow", "ACTIVE USERS"))
        self.pushButton.setText(_translate("MainWindow", "SEND"))

    def open_file_dialog(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(
            None,
            "Open File",
            "",
            "Image Files (*.png)",
            options=options
        )
        if file_name:
            self.message.append(f"!!**!!{file_name}")


